version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgressql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgressql/data/pgdata
    ports:
      - '5432:5432'

  app:
    build: .
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - '8001:8000'

volumes:
  pg_data:
